### PR TITLE
Web interface softer on the eyes

### PR DESCRIPTION
**Pull request by nagyrobi**
Color tweaks to to make the web interface softer on the eyes by using a dark theme, +reducing the go_back refresh to 10 seconds.

### CODE REVIEW

**Comment by nagyrobi** [comment]
kép

**Comment by dgomes** [comment]
I actually prefer the white background 😅

**Comment by nagyrobi** [comment]
Let's make it configurable, then.

**Comment by fvanroie** [comment]
Anything subjective like colors should indeed be configurable, with a sensible default.
Maybe in first instance adding the colors to _user_config_override-template.h_

**Comment by nagyrobi** [comment]
Like this (for current values)?
```
#define HTTP_META_GO_BACK_TIME "15"
#define HTTP_BODY_BACKGROUND "#FFFFFF"
#define HTTP_BUTTON_BACKGROUND "#0af"
#define HTTP_BUTTON_TEXT "#eee"
#define HTTP_BUTTON_REDBACK "#f33"
#define HTTP_BODY_TEXT "#000000"
```
The values are embedded in consts so to make it configurable a bit more rewrite is needed.

**Comment by arovak** [comment]
It is now possible to change the interface colors via `user_config_override.h` and build with the desired color scheme.

for example, the dark template @nagyrobi suggested.
```
// Dark theme
#define D_HTTP_COLOR_TEXT               "#eaeaea"    // Global text color - Very light gray
#define D_HTTP_COLOR_BACKGROUND         "#252525"    // Global background color - Very dark gray (mostly black)
#define D_HTTP_COLOR_INPUT_TEXT         "#000"       // Input text color - Black
#define D_HTTP_COLOR_INPUT              "#ddd"       // Input background color - Very light gray
#define D_HTTP_COLOR_INPUT_WARNING      "#ff5661"    // Warning text color - Brick Red
#define D_HTTP_COLOR_BUTTON_TEXT        "#faffff"    // Button text color - Very pale (mostly white) cyan
#define D_HTTP_COLOR_BUTTON             "#1fa3ec"    // Button color - Vivid blue
#define D_HTTP_COLOR_BUTTON_RESET       "#d43535"    // Restart/Reset/Delete button color - Strong red
```

**Pull request closed without merging**
