### PR TITLE
Add linux emulator platform

### PR DESCRIPTION
**Pull request by thouters**
This adds a linux (lvgl+sdl) emulator based on the existing windows one.
This patch mostly adds extra ifdefs. It just dawned upon me that I forgot to take out lots of debugging printf()'s. I can clean that up. Meanwhile have a look already :-)

### CODE REVIEW

**Comment by fvanroie** [comment]
Thanks, look good! Don't worry about the debug messages.
Just let me know when you're ready for merge.

**Comment by dgomes** [comment]
Nice, looking forward to port this to Mac OS :)

**Comment by fvanroie** [comment]
I've merged the code and created a seperate build environment for it. ALso added the "Execute" action to build&launch the app from within PIO. I just added the linux build to CI too, so it is automatically tested on commits.

A MacOS version might be possible, but I don't own a Mac anymore... so depends on a PR :)

**Comment by fvanroie** [comment]
Thanks @thouters !!

**Comment by dgomes** [comment]
Can we have a Makefile to build the emulator ?

**Comment by fvanroie** [comment]
The native application is also built from PlatformIO just like the MCU's. But you need a couple of per-requisites.
It behaves like a plate, but the configuration options are still hardcoded/defaults at the moment.

Running some tests on it now:
image

I updated the [Compiling ](https://fvanroie.github.io/hasp-docs/#compiling/) section of the docs, but the native environment is only for 0.4.0-dev.

**Pull request merged**
